[[CURRENCIES]]
code="MapCap"
issuer="GBBGQUMVHMRRNQGFXXM7KJL6LH65DGUMVYHFXQXYQ7GKYILOOIV445IB"
name="Map of Pi"
desc="This is a test token that is created to demonstrate Map of Pi capitilization and investment opportunity. It currently hold no value."
image="https://mapofpi-react.netlify.app/token-logo.png"